/**
 * ForgePilot Dashboard — Real Data Aggregation Hooks
 *
 * Replaces static sample data with live aggregation from the backend API.
 * Each hook fetches and transforms data for a specific dashboard metric set.
 */

import { useState, useEffect, useCallback } from "react";

/* ── Types ────────────────────────────────────────── */

export interface TaskSummary {
  title: string;
  taskId: string;
  stage: "plan" | "execute" | "verify" | "report";
  status: "planned" | "running" | "blocked" | "verified" | "shipped";
  risk: "safe" | "review" | "danger" | "blocked";
  detail: string;
  failed?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface SpaceMetrics {
  taskCount: number;
  runningCount: number;
  blockedCount: number;
  verifiedRate: number;
  avgDurationMs: number;
  totalCostUsd: number;
}

export interface ToolMetrics {
  connectorCount: number;
  writableCount: number;
  mockCoverage: number;
  totalCalls: number;
  failedCalls: number;
}

export interface AuditMetrics {
  eventCount: number;
  exportable: boolean;
  traceIdEnabled: boolean;
  sharedLinks: number;
}

export interface DeliveryMetrics {
  reportCount: number;
  autoGenerated: number;
  hasReplay: boolean;
  deliveryStatus: string;
}

/* ── API Fetch Helper ─────────────────────────────── */

async function fetchJson<T>(
  url: string,
  signal?: AbortSignal,
): Promise<T | null> {
  try {
    const res = await fetch(url, { signal });
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

/* ── useConsoleMetrics ─────────────────────────────── */

export function useConsoleMetrics(spaceType?: string) {
  const [metrics, setMetrics] = useState<SpaceMetrics>({
    taskCount: 0,
    runningCount: 0,
    blockedCount: 0,
    verifiedRate: 0,
    avgDurationMs: 0,
    totalCostUsd: 0,
  });
  const [loading, setLoading] = useState(true);

  const refresh = useCallback(async () => {
    setLoading(true);
    const url = spaceType
      ? `/api/v1/forgepilot/spaces/${spaceType}/metrics`
      : "/api/v1/forgepilot/task-console/metrics";
    const data = await fetchJson<SpaceMetrics>(url);
    if (data) {
      setMetrics(data);
    }
    setLoading(false);
  }, [spaceType]);

  useEffect(() => {
    const controller = new AbortController();
    refresh();
    return () => controller.abort();
  }, [refresh]);

  return { metrics, loading, refresh };
}

/* ── useTaskQueue ──────────────────────────────────── */

export function useTaskQueue() {
  const [tasks, setTasks] = useState<TaskSummary[]>([]);
  const [loading, setLoading] = useState(true);

  const refresh = useCallback(async () => {
    setLoading(true);
    const data = await fetchJson<TaskSummary[]>(
      "/api/v1/forgepilot/task-console/queue",
    );
    if (data) {
      setTasks(data);
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    refresh();
  }, [refresh]);

  return { tasks, loading, refresh };
}

/* ── useToolMetrics ────────────────────────────────── */

export function useToolMetrics() {
  const [metrics, setMetrics] = useState<ToolMetrics>({
    connectorCount: 0,
    writableCount: 0,
    mockCoverage: 0,
    totalCalls: 0,
    failedCalls: 0,
  });
  const [loading, setLoading] = useState(true);

  const refresh = useCallback(async () => {
    setLoading(true);
    const data = await fetchJson<ToolMetrics>(
      "/api/v1/forgepilot/tools/metrics",
    );
    if (data) {
      setMetrics(data);
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    refresh();
  }, [refresh]);

  return { metrics, loading, refresh };
}

/* ── useAuditMetrics ───────────────────────────────── */

export function useAuditMetrics() {
  const [metrics, setMetrics] = useState<AuditMetrics>({
    eventCount: 0,
    exportable: false,
    traceIdEnabled: false,
    sharedLinks: 0,
  });
  const [loading, setLoading] = useState(true);

  const refresh = useCallback(async () => {
    setLoading(true);
    const data = await fetchJson<AuditMetrics>(
      "/api/v1/forgepilot/audit/metrics",
    );
    if (data) {
      setMetrics(data);
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    refresh();
  }, [refresh]);

  return { metrics, loading, refresh };
}

/* ── useDeliveryMetrics ─────────────────────────────── */

export function useDeliveryMetrics() {
  const [metrics, setMetrics] = useState<DeliveryMetrics>({
    reportCount: 0,
    autoGenerated: 0,
    hasReplay: false,
    deliveryStatus: "draft",
  });

  const refresh = useCallback(async () => {
    const data = await fetchJson<DeliveryMetrics>(
      "/api/v1/forgepilot/delivery/metrics",
    );
    if (data) {
      setMetrics(data);
    }
  }, []);

  useEffect(() => {
    refresh();
  }, [refresh]);

  return { metrics, refresh };
}
