
services:
  forgepilot:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    image: ${FORGEPILOT_IMAGE_NAME:-forgepilot-studio:latest}
    container_name: ${FORGEPILOT_CONTAINER_NAME:-forgepilot-studio-app}-${DATE:-}
    environment:
      - AGENT_SERVER_IMAGE_REPOSITORY=${FORGEPILOT_AGENT_SERVER_IMAGE_REPOSITORY:-ghcr.io/however-yir/forgepilot-agent-server}
      - AGENT_SERVER_IMAGE_TAG=${FORGEPILOT_AGENT_SERVER_IMAGE_TAG:-1.16.1-python}
      #- SANDBOX_USER_ID=${SANDBOX_USER_ID:-1234} # enable this only if you want a specific non-root sandbox user but you will have to manually adjust permissions of ~/.openhands for this user
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE:-$PWD/workspace}
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${FORGEPILOT_HOME:-$HOME/.forgepilot}:/.openhands
      - ${WORKSPACE_BASE:-$PWD/workspace}:/opt/workspace_base
    pull_policy: build
    stdin_open: true
    tty: true
