apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forgepilot.fullname" . }}-secret
  labels:
    {{- include "forgepilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  LLM_API_KEY: {{ .Values.app.secrets.LLM_API_KEY | quote }}
  DB_PASS: {{ .Values.app.secrets.DB_PASS | quote }}
  REDIS_PASSWORD: {{ .Values.app.secrets.REDIS_PASSWORD | quote }}
